### ISSUE TITLE
Amazon Service Simulator

### ISSUE THREAD

**Issue by tasi333** [jradwan/alexa_tivo_control#12]
Thanks for this awesome Alexa Skill.

So far I've got the local Node.js server setup with the alexa app and the tivo control app, and I'm able to externally access the server through HTTPS, and use the node.js testing utility to issue commands, they work just fine.

I setup the skill on the Amazon developer account per the instructions, uploaded the SSL cert, copied the amazon ID into the config.json file, etc. etc., I followed the instructions in the wiki. 

But when I go to test it on the Amazon Service Simulator, I keep getting the following error:
...
The remote endpoint could not be called, or the response it returned was invalid.
x
Parse Error on Line 1:
The remote endpoint
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got
'undefined'
...

I can't figure out what to do next to resolve this, any help would be appreciated.

Thanks

**Comment by jradwan** [comment]
Do you have the correct endpoint specified on the Configuration page of the skill? What text are you using in the Service Simulator? 

My endpoint is handling the certificate, so I don't have any experience with uploading one to the developer web site.

**Comment by tasi333** [comment]
I'm using the endpoint I configured and tested remotely (I used a custom port number not 443):
https://nodejs.domain.com:PORT/alexa/tivo_control

The SSL was generated and managed by the endpoint, but as a part of my troubleshooting, I decided to upload the cert to the developer site to see if it made a difference (it didn't).

I just used "Pause" (no quotes) as the text in the service simulator.  I tested this intent directly on the endpoint, and it works.

Thanks for the quick response.

**Comment by TRingo1** [comment]
I think you need to use 443

**Comment by tasi333** [comment]
@TRingo1 , you were right!  I wonder why we can't use a custom port.

It's working now, thanks for the pointer!

**Comment by jradwan** [comment]
Thanks, @TRingo1. I'll close this issue.
