### ISSUE TITLE
Wiki Install Step 14 (certificates and external HTTPS access)

### ISSUE THREAD

**Issue by MikelMD** [jradwan/alexa_tivo_control#14]
While I understand that creating the self-signed cert is covered in another section, and creating the DDNS is also outside this section, as well as port forwarding in the FW - for which I would be happy to add the DDNS and FW section.  I have been stuck at the c/p of the certificate (the checkbox is never green) and my test error is: The remote endpoint could not be called, or the response it returned was invalid.
I can access the https:\\myddns.net\alexa\tivo_control from the web as if I was going to http:\\ip address:808]alexa\tivo_control.  So I know I can reach the internal Alexa-app-server.  

I have surfed the boards and submitted support tix to Amazon to no avail.  I thought perhaps someone would catch the issue?

**Comment by jradwan** [comment]
So you've reviewed this document:

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/testing-an-alexa-skill#create-a-private-key-and-self-signed-certificate-for-testing

Specifically:

> When Alexa sends a request, your service must present your certificate. The subject alternate name in your certificate must match the domain name of your endpoint.
> 
> For example, assume your service’s endpoint is at https://wiseguy.mywebserver.com/wiseguy. In this case, your endpoint needs to present a valid certificate in which the subject alternate name is set to wiseguy.mywebserver.com. You specify this in the configuration file that you use to generate the certificate.
> 
> Configure your endpoint to present this certificate. The specifics for doing this depend on how you are hosting the web service. For example, if you use Amazon Web Services Elastic Beanstalk, you upload the certificate file using the AWS Command Line Interface.

It sounds like maybe your certificate isn't valid for the URL? Not exactly sure.

**Comment by MikelMD** [comment]
Yes, I know that doc intimately ;)  So, yes, for example, my domain is https://mydomain.ddns.net and in my [subject_alternate_names], I have DNS.1 = mydomain.ddns.net - unless I am missing something - its that easy. Therefore, in my HTTPS endpoint (on AWS) I have https://mydomain.ddns.net/alexa/tivo_control

**Comment by jradwan** [comment]
And when you hit that HTTPS endpoint, your browser properly recognizes the certificate and shows the green padlock for a secure connection?

Hopefully someone else who's done this with a self-generated certificate can chime in and help. I'm using a LetsEncrypt certificate directly on my own domain.

**Comment by MikelMD** [comment]
Thx - I did fix the "not trusted" aspect of the certificate. So not when I go to https://mydomain.ddns.net/alexa/tivo_control is shows a lock - but still no go on the AWS site.  I am going to try LetsEncrypt.  Q. In the Amazon apps, SSL configuration, you c/p the cert - is the checkbox grey or green?

**Comment by jradwan** [comment]
By c/p you mean copy/paste? Because I don't have to upload my certificate to Amazon since the cert is installed on my web server.

![image](https://cloud.githubusercontent.com/assets/11047158/22076765/770d6526-dd7f-11e6-9b3d-ba7df1541462.png)

**Comment by MikelMD** [comment]
Yes.  That is where I have an issue.  I spent time adding the Self-Signed cert in my mac Keychain so that the browsers accepted the cert.  -thanks for that one! I added a PCKS12 to my Java Keystore and that looks good.  However, no matter what I do when I copy/paste the cert that SSL Cert checkbox is grey and I get the "There was an exception during the SSL hand shake. Please check the certificate you have provided." in the service response in the test.  
It looks like I am going to turn to LetsEncrypt - Since that does work.
And, for the past two weeks I have been trying to get anyone from amazon to help me w/ the grey self-cert issue.

I am going to close this out - unresolved.  I think we have done all we could.  If Amazon responds or if I do find the fix, I will post.

I will look at AWS lambda, too.

**Comment by jradwan** [comment]
Ok, sorry Mike! Hope you can get it figured out.

**Comment by TRingo1** [comment]
I may be able to help but won't be back til next week. If still working on this issue I'll chime in.

**Comment by MikelMD** [comment]
That would be great!

**Comment by MikelMD** [comment]
To be clear, this is the correct "path" that is in the AWS app, the Endpoint Configuration section, and via browser, is the same, https://mydomain.ddns.net/alexa/tivo_control?  Meaning the page both got to is the page that state: This is a simple testing utility to POST to your endpoint and simulate an Alexa request.

More:  When I go to the above website and execute a pause, so it looks like if I get the the website, the code executes.

Loading apps from: apps
[2017-01-21T15:36:56.151Z] Currently controlling: Mini (w.x.y.z)
[2017-01-21T15:36:56.155Z]    Loaded app [alexa_tivo_control] at endpoint: /alexa/tivo_control
[2017-01-21T15:36:56.155Z]    package.json not found in directory node_modules
[2017-01-21T15:36:56.155Z] httpsEnabled is true. Reading HTTPS config
[2017-01-21T15:36:56.179Z] Listening on HTTPS port 443
[2017-01-21T15:36:56.180Z] Listening on HTTP port 80
[2017-01-21T15:48:17.684Z] preRequest fired
[2017-01-21T15:48:27.495Z] preRequest fired
[2017-01-21T15:48:27.496Z] NO_INTENT_FOUND
[2017-01-21T15:48:33.638Z] preRequest fired
[2017-01-21T15:48:33.639Z] QueuedCommands: PAUSE
[2017-01-21T15:48:33.646Z] Connection Created
[2017-01-21T15:48:33.662Z] RECEIVED: CH_STATUS 0600 LOCAL
[2017-01-21T15:48:33.969Z] Sending Prefixed Command: IRCODE PAUSE
[2017-01-21T15:56:59.087Z] preRequest fired
[2017-01-21T15:56:59.089Z] QueuedCommands: PAUSE
[2017-01-21T15:56:59.091Z] Connection Created
[2017-01-21T15:56:59.106Z] RECEIVED: CH_STATUS 0600 LOCAL
[2017-01-21T15:56:59.410Z] Sending Prefixed Command: IRCODE PAUSE

**Comment by jradwan** [comment]
Yes, you should have that same path on the Configuration tab of your skill (Service Endpoint Type HTTPS), which is the same path you can use to get to the built-in tester. The Test tab of the skill should also work using that same endpoint. Looking at your log above, it would appear to be working.

**Comment by MikelMD** [comment]
Then the only disconnect is between the AWS app and the website on my PC and I have no idea where the issue is.  I wonder if anyone else is having the self-cert issue with the Alex-App-server?

**Comment by greenpad2** [comment]
Mike, did you figure this one out?  I am attempting to use the self-signed cert but really don't know how to get https working on my machine.  If I look at http://mydomain.com:8080/alexa/tivo_control externally, it works, but I don't know how to get https working.  I'm on windows--do I need to install a web server through IIS and then forward the traffic?  

Thanks

**Comment by MikelMD** [comment]
Hey, yes and no. I managed to get the service working. What failed is the self cert. I am on a Mac. So I stared the app server and it listened on port 443 and 8080. I was able to go to an outside machine and get the test web page (yes u need to port forward to the machine ip). What failed is Amazon. I would get an error and I could not find a fix ( search MikelMD).

**Comment by jradwan** [comment]
Hey guys ... I came across this [Home Asssistant](https://home-assistant.io/) project and wondered if some of the setup references might work for TiVo Control as well. For example, a Lambda-based proxy setup for https:

https://community.home-assistant.io/t/aws-lambda-proxy-custom-alexa-skill-when-you-dont-have-https/5230

Also related is the encryption setup:

https://home-assistant.io/blog/2015/12/13/setup-encryption-using-lets-encrypt/

I might play around with this project just to get more experience and see what it can do. richie_p over on the TiVo Community Forum [mentioned](http://www.tivocommunity.com/community/index.php?threads/tivo-ui-control-via-telnet-no-hacking-required.392385/page-35#post-11150625) he used this along with [emulated_hue](https://home-assistant.io/components/emulated_hue/) to do basic channel changes which is what triggered me to do a little research on it.

**Comment by jradwan** [comment]
Hello again!

The Lambda HTTPS proxy service worked! I was able to get the Alexa skill to use the Lambda service, which forwards the traffic to the alexa-app-server via HTTP.

Follow the instructions [here](https://community.home-assistant.io/t/aws-lambda-proxy-custom-alexa-skill-when-you-dont-have-https/5230) to create the Lambda function. In the code (which is based on [this](https://github.com/sarkonovich/Alexa-Nest/blob/master/lambda_passthrough.txt)), replace the 'amzn1.ask.skill.xxxx' string with your TiVo Control Alexa skill's Application ID from the Skill Information tab. Remove the space between the single quote and the http:// and replace THAT string with the address of your alexa-app-server (don't forget the closing single quote, it's missing in the original code). For example, mine looked like this (sample values, but you get the point):

```
        // A list of URL's to call for each applicationId
        var handlers = {
            'appId':'url',
            'amzn1.echo-sdk-ams.app.my-tivo-control-skill':'http://www.mysite.net:33333/tivo_control'
        };
```

Set up port-forwarding on your router as desired, so you can access the Alexa Tester page of alexa-app from the internet. In the example above, I forwarded 33333 to port 8196 (as defined in server.js) on my internal server running alexa-app-server.

On the Configuration page of your TiVo Control skill, switch from HTTPS to Lambda and paste in the ARN of your Lambda proxy function. Now go to the Test page and see if it works.

In my testing, you can't use the alexa-verifier with this setup, so you'll need verify:false in server.js. You can set debug:false to disable the Alexa Tester too once you know it's working. That should at least prevent people from easily accessing the Alexa Tester but could still allow non-Amazon-sent JSON requests. As usual, use at your own risk.

Hope this helps ... let me know if it works for you guys. If it does, I'll try writing it up again and adding it as an option to the installation instructions. One thing I realized after testing is that I didn't change the SSL certificate tab on my TiVo Control skill, it was still " My development endpoint has a certificate from a trusted certificate authority" so I'd be curious what issues (if any) you guys have trying to use this method.

**Comment by greenpad2** [comment]
I went the other direction, using the lets_encrypt link you put in your previous entry.  I was able to use this program to get a certificate installed in IIS:

https://github.com/Lone-Coder/letsencrypt-win-simple

I've now got a simple https://mydomain.com page working.  But I can't figure out how to get this working with nodejs.  I'm assuming I need to get IIS to serve up the certificate then pass through to port 8080 for me, but I can't figure out how to do that.  

The lambda stuff seems cool but I'm too cheap to pay them to host this.  Thanks for looking into it though.

**Comment by greenpad2** [comment]
Getting closer!  I had to install URL rewrite here:

https://www.iis.net/downloads/microsoft/url-rewrite

It then asked me install yet another extension.  After that I set up a reverse proxy to http://192.168.1.101:8080 and I can now go to https://mydomain.com/alexa/tivo_control and see the page!

I loosely followed the instructions detailed here:

http://blog.lint.at/iis-as-reverseproxy-with-ssl-offloading/

Now I just need to see what amazon does with my new certificate

**Comment by greenpad2** [comment]
IT WORKS!  Granted, I need to learn it and tune it, but it works!  Using the above settings I was able to tell amazon that my domain has a registered certificate--it checked and it worked fine.  I then installed node.exe server.js as a service and tried it all out.  

I did have an issue during install--I'll open another issue on that.  Thanks!

**Comment by jradwan** [comment]
I had a discussion with another user on a different site about getting this to work with a self-signed certificate and SSL in alexa-app-server. Here are the instructions they used to get it working.

Start with the instructions [here](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/testing-an-alexa-skill#create-a-private-key-and-self-signed-certificate-for-testing). You'll need OpenSSL installed for your platform. 

Now here's what they did (I cleaned up the instructions a bit):

> In a command prompt that runs as admin type:
> 
> `openssl genrsa -out private-key.pem 2048`
> 
> This will generate your private-key.pem in whatever directory you are in when you run it. Then: 
> 
> `openssl req -new -x509 -key private-key.pem -out cert.cer -days 365 -config configuration.cnf -out cert.cer`
> 
> (configuration.cnf is the file you created in step 2 of the above link) This will make cert.cer (in the current directory). Put both private-key.pem and cert.cer in $ALEXA_HOME\examples\sslcert (overwrite the default files).
> 
> Finally, add these lines to your server.js:
> 
> ```
> httpsEnabled : true,
> httpsPort : 443,
> privateKey: 'private-key.pem',
> certificate: 'cert.cer'
> ```
> Open the cert.cer file in a text editor and copy it to your clipboard. On the "SSL Certificate" tab of your skill select "I will upload a self-signed certificate in X.509 format." Copy the contents of cert.cer into the text box that appears. 
> 
> Now save your skill and restart alexa-app-server.

I've linked to this issue discussion in Step 14 of the Installation Instructions (funny how this is issue 14 relating to step 14 😉). Hope this helps (and thanks to jadekitten on the TiVo Community Forum for getting this working and sending me the details).

**Comment by dalabera** [comment]
I was able to setup your alexa skill after struggling with so many issues. For example here the url was missing the default "alexa" word.
`// A list of URL's to call for each applicationId
        var handlers = {
            'appId':'url',
            'amzn1.echo-sdk-ams.app.my-tivo-control-skill':'http://www.mysite.net:33333/alexa/tivo_control'
        };`

**Comment by jradwan** [comment]
Sorry you had issues but that was just a sample value. I use a custom URL without "alexa" in the path, for example. So whatever your endpoint URL is, you fill it in there. Glad you got it working though!

**Comment by cwoody222** [comment]
dalabera, I'm trying the same as you were. Can you explain why you used 33333 as the port and if how you set up any port forwarding on your router, assuming you had to?

My app is working locally but i'm getting this error with my URL
"errorMessage": "No url found for application id"

I'm using:
'http:// < my IP> :8080/alexa/tivo_control'

**Comment by jradwan** [comment]
I just used 33333 as an example ... it can be anything you want. You need to avoid port numbers below 1024 so making up a random number (security through obscurity) is usually the way to go.

**Comment by cwoody222** [comment]
I got it working!

So cool, thanks for your help and efforts making it!

**Comment by jradwan** [comment]
Excellent! Glad to help ...
