### ISSUE TITLE
Missing file or incorrect documentation?

### ISSUE THREAD

**Issue by jandreaucodes** [jradwan/alexa_tivo_control#2]
The instructions say to run 

> node server.js

But there's no server.js anywhere in the repo. Running app.js doesn't result in starting the Alexa App Server, so I'm not sure where to take it from there.

**Comment by jandreaucodes** [comment]
I think I missed the first instruction about Alexa App Server. Which specific App server are you relying on? Google suggests there's a handful available.

**Comment by jradwan** [comment]
Sorry I missed this ... never got a notification from GitHub.

I'm using [alexa-app](https://www.npmjs.com/package/alexa-app). server.js is in the base install directory for that (same level as the apps and node_modules directories).

**Comment by jrlambs** [comment]
I'm having the same issue.. I'm almost positive that my folder structure is wrong... or maybe something has changed with alexa-app.  

I'm installing using these commands
git clone https://github.com/jradwan/alexa_tivo_control.git
cd alexa_tivo_control
npm install alexa-app-server --save
npm install alexa-app --save
npm install
cp example_config.json config.json
--Edit the config file

when I'm done if I search for server.js (find . | grep server.js) I get the following list
./node_modules/alexa-app-server/examples/server.js
./node_modules/hawk/test/server.js
./node_modules/hawk/lib/server.js

the overall structure of the alexa_tivo_control directory is:
./docs/
./node_modules/
./node_modules/alexa-app-server
./node_modules/alexa-app

^^ and a bunch of other modules.

I can go into /node_modules/alexa-app-server/examples and run "node server.js" and it starts up, but doesn't register your tivo control app.  Any thoughts on what I'm doing wrong?  THANK YOU!

**Comment by jrlambs** [comment]
Ah, it helps to type it out I guess... I JUST found this.. 
https://github.com/matt-kruse/alexa-app-server

the most interesting point being the suggested folder structure.

```
+--- server.js
+--- sslcert
+--- apps
     +--- alexa-app-1
          +--- package.json
          +--- index.js
          +--- node_modules
     +--- alexa-app-2
          +--- package.json
          +--- index.js
          +--- node_modules
+--- public_html
     +--- index.html
```



so this is what I ended up with

```
node_modules
   +--- alexa-app-server
      +---tivoserver
         +---apps
            +---alexa_tivo_control [THIS REPO]
      server.js (copied from alexa-app-server/examples/server.js)
```

**Comment by jradwan** [comment]
Sorry for the confusion. I wrote out the installation instructions after I had most of the functionality working, so a lot of it I wrote from memory and didn't actually _check_. I'll try to clean that up ...

**Comment by TRingo1** [comment]
I have mine installed on my macbook, here is the directory structure and locations:

/Users/me/NodeJS/node_modules/alexa-app-server/examples/apps/alexa_tivo_control/
```
node_modules
 +---alexa-app-server
     +---examples
	     +---apps
		     +---alexa-tivo-control
			     +---config.json  (this is edited to your tivo ip address)
				 +---package.json
				 +---app.js
		 +---server.js
		 +---server
			+---login.js
		 +---sslcert
			 +---cert.cert
			 +---private-key.pem
		 +---public_html
			+---index.html
```

Also in i had to utilize NAT on my firewall due to other apps using my 443 port on my macbook.  amazon needs to talk only to port 443, and cannot be changed, at least not that im aware of.  Until i changed the port i was starting server.js on for https, it would not start correctly.

**Comment by jradwan** [comment]
Ok everyone, sorry for the confusion. I took some time today to set up my environment mostly from scratch and see now how the instructions were unclear. I've updated them accordingly so hopefully they're more useful now. Let me know what you think!

**Comment by jradwan** [comment]
I've also added instructions for installing on Windows, so I'm closing this issue now.
