### ISSUE TITLE
Server 500 when hosting my own server.

### ISSUE THREAD

**Issue by spherular** [jradwan/alexa_tivo_control#21]
You glossed over the server hosting and this is where I'm having problems. What server did you use?

I got the app up and running on my home windows pc using a cert and https on port 443. When I try and get alexa to trigger the commands I get the follow error :

There was an error calling the remote endpoint, which returned HTTP 500 : Internal Server Error

Should I be using Lambda or Heroku?

Any help in this area would be appreciated.

Thanks

**Comment by jradwan** [comment]
I "glossed" over that since it's complicated and I don't want to have to document getting an SSL certificate, setting up https, etc. I'm running Apache on my local web server and then proxying the 443 traffic from Apache to the alexa-app-server.

You don't need Lambda or Heroku (I had to Google that one) ... everything is running in alexa-app-server on your PC. As mentioned in the instructions, though, your endpoint needs to be accessible from the internet, as defined on the Configuration page of the Alexa skill in the developer console.

Where are you seeing the 500 error? From the tester alexa-app-server tester, or the Alexa Skill service simulator?

**Comment by spherular** [comment]
Thanks for the prompt response.

I see it on the test section on the amazon developer website. When i type in https://xxx.zxx.com/alexa/tivo_control i get the correct tester website. Also when i trigger test the server responds with "preRequest fired"

I imagine there is some difference between the triggered events that is causing the problem. When I fire it directly I get different sessionId, applicationId and userId to the ones I see on the amazon website.

Any ideas and thanks again!

**Comment by MikelMD** [comment]
R u using a self-signed cert?

**Comment by jradwan** [comment]
I do see different sessionId, applicationId, and userId values using the service simulator vs. the alexa-app-server tester, so I don't think that's it.

I removed the preRequest stuff from my alexa-app-server.

**Comment by spherular** [comment]
Yes I'm using a cert created with openssl

**Comment by spherular** [comment]
So would removing the preRequest stuff possibly help me? Where is that?

**Comment by jradwan** [comment]
I don't know if it would help, but I don't use it. It's in the server.js for alexa-app-server (/usr/local/alexa-app-server/examples or your Windows equivalent).

**Comment by spherular** [comment]
I just commented it out and it made no difference. Same HTTP 500 error.

**Comment by jradwan** [comment]
Any details in the app.log (/usr/local/alexa-app-servfer/examples/log)?

**Comment by spherular** [comment]
I have no log in that location.

**Comment by jradwan** [comment]
Whoops, forgot you're running on Windows. I have alexa-app-server on my Linux box send all console output to a log file. In your case, assuming you're starting node-js from a command-line, the messages should be scrolling in that same window. Does anything appear in that console when the service simulator gets back the error 500 from your request?

I did some searching and came across [this thread](http://www.tivocommunity.com/community/index.php?threads/which-tivo-api-for-show-list-and-forced-playing-on-tivo.539075/page-2#post-10945498) on the TiVo Community Forum with the same error back in July. Was that you? 😉

**Comment by spherular** [comment]
I just have the same console message of preRequest fired.

It wasn't me. I only got my Dot and christmas so am a little late to the alexa party!

**Comment by spherular** [comment]
My alexa app id is still set to " " is the config.json file. Is that correct? Just wondering if that should be set to the one i have created on developers.amazon.com

**Comment by jradwan** [comment]
Ok, so does the alexa-app-server tester work (step 11 in in the instructions)? In other words, if you go hit https://xxx.zxx.com/alexa/tivo_control, select a Type of "Intent Request" and an Intent of "Pause" what happens?

It sounds like maybe the request from the Amazon service simulator isn't making it to your server for some reason.

And yes, you should fill in your appId in config.json. Make sure you restart node-js after doing that.

**Comment by spherular** [comment]
It does work. I can use my cell phone on LTE and control my tivo through the https website.

**Comment by spherular** [comment]
That did it!!!!!! Adding the correct app id to the config file. I don't think I saw that in the instructions.

**Comment by spherular** [comment]
Thanks for everything!

**Comment by jradwan** [comment]
Ha, excellent! Glad it's working!

**Comment by MikelMD** [comment]
Congrat's on getting it to work.  If I may, when you added your self-signed cert, on Amazon, the checkbox is it grey or green and checked?

**Comment by spherular** [comment]
It's grey...it only turns green if it's a cert that can be used for public use.
