### ISSUE TITLE
Launch Plex

### ISSUE THREAD

**Issue by spherular** [jradwan/alexa_tivo_control#22]
I have found that when I try to launch plex the system takes me into the "What to Watch Now" menu instead of Find TV, Movies & Videos. How do I debug and edit the remote presses being used to launch these applications - TiVo has a habit of moving menu items so changing it myself would likely be easier. Thanks

**Comment by jradwan** [comment]
First, in the log, make sure Alexa is "hearing" you correctly. I've seen the same problem, actually, when launching Plex where for whatever reason Alexa hears incorrectly. The debug log should show what is actually being launched (WTWN or Plex).

Next, the order of providers is determined by their order in the video_provider_order and audio_provider_order arrays (lines 18 and 19 in app.js). I have noted in the [To Do List](https://github.com/jradwan/alexa_tivo_control/wiki/To-Do-List) that this order seems to sometimes be different on different boxes. I may need to come up with a better/easier way to customize this. But for now, you can just move the "strings._provider-name_" elements around in those arrays. The function buildProviderNavigation (line 1333 in app.js) is what goes through those arrays and creates the actual navigation macro commands (i.e., determines how many "down" commands are needed).

If Alexa is hearing the utterance correctly and it's still not navigating to the proper place, the other possibility is a delay in the TiVo responding to the sent commands. You can play with the "timeToWait" parameter of sendNextCommand to increase the delay (in milliseconds). Currently there are delays of 300ms and 700ms depending on where the code is being called from.

**Comment by jradwan** [comment]
I increased the delay after a "TELEPORT TIVO" command from 700ms to 2500ms (2.5 seconds). Yes, this slows down the overall macro performance, but should help to make sure the TiVo is sitting on TiVo Central (especially after exiting an app like YouTube, Plex, Pandora, etc.) before sending the remaining navigation commands.
