### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Dillonmartine** [jradwan/alexa_tivo_control#23]
Perhaps I over looked this.. but if I open the https page to the internet, wont this mean anyone who browses to the address could control my TiVo? What security measures do you  have in place?

**Comment by jradwan** [comment]
Yes, that's true. There are no security measures in place at this time ... it's an unofficial skill, just for tinkering. You can change/obscure the endpoint so alexa-app-server doesn't "listen" on just /alexa (I have mine set to a random string). There's also the [alexa-verifier](https://github.com/alexa-js/alexa-verifier) you can enable in alexa-app-server (verify=true in server.js) but I have not had the time to play with that (PRs welcome).

It's up to you to decide if it's worth the risk to mess around with.

**Comment by jradwan** [comment]
I did a little testing with regards to this today.

In the latest version (>=3.0.0) of alexa-app-server, you can turn on the alexa-verifier by adding these lines to your server.js:

```
  debug: false,
  verify: true
```

So, for example:

```
var AlexaAppServer = require("../index.js");

AlexaAppServer.start({
  server_root: __dirname,
  port: 8080,
  debug: false,
  verify: true
});
```

With verify on, alexa-app-server will only accept requests from Amazon. If you try to access the endpoint via a browser (i.e., to get to the tester) you'll get:

```
{"status":"failure","reason":"The signaturecertchainurl HTTP request header is invalid!"}
```

That should prevent just anyone from controlling your TiVo with the endpoint exposed to the internet. I've added step 18 to the install instructions with this information as well. 

Thanks for raising the point.
