### ISSUE TITLE
sample utterances (w/optional slots, like +GENRE+ and +TIVOBOXRM+)

### ISSUE THREAD

**Issue by greenpad2** [jradwan/alexa_tivo_control#24]
When I went to copy/paste sample utterances, I found that a good number of them had +SOME_STRING+ in them, such as +GENRE+.  Amazon didn't like this, so I just got rid of the plus signs.  Is this a sign I left something out when I got this all running?  I have a feeling I lost some functionality by changing all of those. 

Thanks!

**Comment by jradwan** [comment]
Yes, this is due the addition of optional slot utterances by @dominicankev, which requires [this pull request](https://github.com/alexa-js/alexa-utterances/pull/24) for alexa-utterances. That PR hasn't been merged into the main alexa-utterances code yet, so for now you'll need to make that change manually. I mention this in the [release notes](https://github.com/jradwan/alexa_tivo_control/releases/tag/0.4.0-alpha) for v0.4.0 but it's easily missed.

If you don't want to modify alexa-utterances, just replace the + with the corresponding curly brace. For example:

`ListChannels for my channels by +GENRE+` becomes `ListChannels for my channels by {GENRE}`

and

`PutOn put on {CHANNELNAME} in +TIVOBOXRM+` becomes `PutOn	put on {CHANNELNAME} in {TIVOBOXRM}`

If you don't do this, all you lose is the optional utterances used for one-time channel changes on a TiVo in another room without having to switch to it first (i.e., "Alexa, tell TiVo to put on ESPN in Family Room") and listing channels by genre (i.e., Alexa, tell TiVo to list my channels by comedy").

Let me know if that works for you.

**Comment by greenpad2** [comment]
Thanks!  I'll go change things to curly braces.  I'm not sure I understand the purpose of the plus signs but I'll keep reading.

**Comment by jradwan** [comment]
Using the plus signs was just @dominicankev's method of marking a slot as optional for alexa-utterances. His PR is the code that changes the + to the { or } for when they appear in the Alexa Tester to copy into the skill's utterances.

**Comment by jradwan** [comment]
Here are the required manual [code changes](https://github.com/alexa-js/alexa-utterances/pull/24/files#diff-168726dbe96b3ce427e7fedce31bb0bc).

**Comment by jradwan** [comment]
Since the PR still isn't merged, for now I'm including a [patched version of the index.js](https://github.com/jradwan/alexa_tivo_control/blob/master/examples/alexa-utterances_index.js) file for alexa-utterances in the examples directory. I updated Step 6 of the [installation instructions](https://github.com/jradwan/alexa_tivo_control/wiki/Installation-Instructions) to include applying this patch.
