### ISSUE TITLE
Order of video providers on different TiVo boxes

### ISSUE THREAD

**Issue by jradwan** [jradwan/alexa_tivo_control#25]
It would appear that the order of the video providers is different on different TiVo boxes. For example, comparing my Bolt and Roamio Plus:

![image](https://cloud.githubusercontent.com/assets/11047158/24124107/8f1c9788-0d98-11e7-8dcd-19b6324dea37.png)

It's strange, too, that the WWE app has a different name on my two boxes. I'm not sure why TiVo would order/name these differently. I probably need to make a change to config.json that allows the end-user to customize the order of these providers.

If other people could post the order they're seeing on their own TiVos (with model information), that would be helpful.

**Comment by brandonandsue** [comment]
Roamio Pro has same list as Bolt.

**Comment by jradwan** [comment]
To clarify, do you mean _your_ Roamio Pro has the same order as _my_ Bolt above?

**Comment by brandonandsue** [comment]
Yes

**Comment by jradwan** [comment]
Great, thanks! Maybe this isn't a problem after all and it's just something weird with my Roamio Plus.

**Comment by jradwan** [comment]
Closing as this seems to be an issue with just my one box. The current order of video providers (that I'm aware of) is:

_Video_
Netflix
HBO Go
Amazon Video (Prime)
Amazon Video
Xfinity on Demand
Hulu
YouTube
MLB.tv
Plex
VUDU
Epix
HSN
Vevo
The Alt Channel
FlixFling
Toon Goggles
WWE
Yahoo
YuppTV

_Audio_
iHeartRadio
Pandora
Plex
Spotify
Vevo
