### ISSUE TITLE
Update code to latest changes

### ISSUE THREAD

**Issue by dalabera** [jradwan/alexa_tivo_control#32]
Thank you for building this tool. I spent couple of hours in order to install the skill. 
Just wanted to ask if you can include the package.json in the builds from the zip files and repository. I was getting erros as the alexa_app_server installed was a lower version than the one require. 

  "dependencies": {
    "alexa-app": "^4.0",

**Comment by jradwan** [comment]
package.json _is_ included in the zip file releases. But yeah, I haven't built a new release (v0.5.0) since adding that alexa-app 4.0 dependency, sorry. If you just download the latest commits from the repository, though, you'd have the up-to-date package.json.

**Comment by jradwan** [comment]
I've published [v0.5.0](https://github.com/jradwan/alexa_tivo_control/releases/tag/v.0.5.0-alpha) which should address this.
