### ISSUE TITLE
Service Simulator cannot reach endpoint

### ISSUE THREAD

**Issue by sgtstadanko** [jradwan/alexa_tivo_control#33]
Hi,

I am having an issue getting the developer console service simulator to be able to reach my https server.  I have the server.js running under https on linux. I have working DDNS and port forwarding of 443 to the server.  I am able to pull up the local tivo_control simulator via the URL i have registered in Amazon and issue working commands, but when i try it through the skill service simulator i get:
"The remote endpoint could not be called, or the response it returned was invalid."
I have the correct HTTPS URL registered and the applicationID is in the config.json. I have restarted server.js a few times.  I dont even see it hit the console logs.

Any ideas would be much appreciated.  Thanks!

**Comment by sgtstadanko** [comment]
Nevermind.  I swapped it over to Lambda and it works fine.

**Comment by jradwan** [comment]
Sorry ... I was out of town this week on vacation. Glad you got it working.
