### ISSUE TITLE
Systemd Startup Script

### ISSUE THREAD

**Issue by sgtstadanko** [jradwan/alexa_tivo_control#34]
Anyone have any luck with a startup script for systemd (ubuntu 15.04)? The example provided is for redhat style init.d and all the node.js systemd scripts I have found don't work properly because I cant reach /alexa/tivo_control when node is running from it.  I could hack up a shell script and have it execed by rc.local, but prefer to have it play nice with systemd and have a log file somewhere.

**Comment by jradwan** [comment]
I'm using the init.d-style startup script on Ubuntu 17.04 so I haven't tried systemd. Maybe this would get you pointed in the right direction?

https://nodesource.com/blog/running-your-node-js-app-with-systemd-part-1/

**Comment by sgtstadanko** [comment]
Thanks. That did the trick.  The issue was in server.js. It was using a relative path server root so none of the app loaded.

For future reference this is what I did:
server.js changed server_root line to absolute path

server_root: '/usr/local/node_modules/alexa-app-server/examples'

then

touch /lib/systemd/system/alexa.service
added to it:
[Unit]
Description=server.js - making your environment variables rad
Documentation=https://example.com
After=network.target

[Service]
Environment=NODE_PORT=8081
Type=simple
User=root
ExecStart=/usr/bin/node /usr/local/node_modules/alexa-app-server/examples/server.js
Restart=on-failure

systemctl daemon-reload
systemctl start alexa

[Install]
WantedBy=multi-user.target

**Comment by jradwan** [comment]
Great! I've added a link to this issue in step 9 of the installation instructions for people who want to use systemd.
