### ISSUE TITLE
error help

### ISSUE THREAD

**Issue by cwoody222** [jradwan/alexa_tivo_control#35]
Moved from: https://github.com/natejgreene/alexa_tivo/issues/6

Thanks for the help Jeremy! Your branch had much more instructions so I started over.  Looks like I'm stuck at step 11, the test page on my local host.  I'm assuming it's an open port issue or something.  If so, I'll have to play around with my router (a standard issue Verizon Fios).

Everything so far up to then went fairly smoothly. Perhaps an error when I installed the Amazon Web Server, I'm not sure.  But I do have the new directories shown after that, so I think it installed correctly.

Unless you have any other ideas around my issue not being a port forwarding issue, that's what I'm going to try.  FYI: I'm just getting: Cannot GET /alexa/tivo_control

**Comment by jradwan** [comment]
Port forwarding doesn't make a difference when you're testing internally, that would only be when you get to the part where the Alexa skill on Amazon's servers needs to talk to your alexa-app-server running on your local machine.

That error would imply a mismatch between the endpoint URL you have set in server.js (app_root) and what you're putting into your browser. If you look in the log file for alexa-app-server (under $ALEXA_HOME/examples/log/app.log) you should see the listening endpoint listed, like this:

```
loading apps from: /usr/local/node_modules/alexa-app-server/examples/apps
[2017-07-09T03:22:03.729Z]    loaded app [alexa_tivo_control] at endpoint: /alexa/tivo_control
[2017-07-09T03:22:03.731Z]    loaded app [hello_world] at endpoint: /alexa/hello_world
[2017-07-09T03:22:03.733Z]    loaded app [number_guessing_game] at endpoint: /alexa/number_guessing_game
[2017-07-09T03:22:03.734Z] listening on http://192.168.1.61:8196
```

You should then be able to point your browser to (using the example above):  http://192.168.1.61:8196/alexa/tivo_control and see the tester.

**Comment by cwoody222** [comment]
OK, some forward motion :)  I can now access the tester locally and it works (commands are sent and received).  I'm using this http://localhost:8080/alexa/tivo_control

Following your instructions here to set up Lambda to set my AppID and my URL.  I'm getting error: "errorMessage": "No url found for application id"

My app is showing me this:
loaded app [alexa_tivo_control] at endpoint: /alexa/tivo_control
...
listening on http port 8080

So I'm setting my URL as 'http:// < my IP> :8080/alexa/tivo_control'

Is that right?  I'm trying a bunch of combinations of port forwarding within my router but I'm not even sure if my URL is correct or if I need to do any port forwarding.  Just need to get it working from Alexa, it's working locally!

**Comment by cwoody222** [comment]
Just to close this thread out; I was able to get it working!

It seems the error I was receiving wasn't serious; and wasn't keeping it from working.  The URL I had set was correct and I just had to forward the port and that was it.

Thanks for the help and for creating this!

**Comment by jradwan** [comment]
You're welcome, and glad you got it working!
