### ISSUE TITLE
How to select netflix account?

### ISSUE THREAD

**Issue by efortenberry** [jradwan/alexa_tivo_control#36]
Is there a way to modify the actions when opening Netflix to select an account?

**Comment by jradwan** [comment]
Not really. Once you've launched Netflix (or any app, really, like Pandora, YouTube, etc.) the only thing you can really have the skill do is send individual remote commands (like "Alexa, tell TiVo to send command down" and "Alexa, tell TiVo to send command enter" to control the app. A little cumbersome.

But now that I'm thinking about it, you _could_ write some custom intents/utterances to send your own set of command macros. Maybe I could add something like "Alexa, tell TiVo to execute macro \<name\>" and let the macro be a definable list of remote commands the user could maintain in another config json file. 

Hmm, interesting. I'll add this as a possible enhancement.

**Comment by efortenberry** [comment]
That would be great to have a way to define and execute our own commands!  That way we can string multiple together to enable a better experience.  Ideally I'd like to open some of these apps, then execute a search and play the first result, or better yet just to launch an app and "continue watching" whatever series we were watching.

**Comment by jradwan** [comment]
I'll track this in issue #38.

**Comment by jradwan** [comment]
@efortenberry, check out issue #38 and my latest commits for my first attempt at the macro functionality and let me know what you think!
