### ISSUE TITLE
User-defined command macros

### ISSUE THREAD

**Issue by jradwan** [jradwan/alexa_tivo_control#38]
Brought up in issue #36, add an intent/utterance that allows the user to define and launch a custom chain of macro commands. 

At a high-level, this would require a new JSON config file (for the macro definition), ability to pause/sleep a macro (to allow for apps to launch, screens to load, etc.), plus the code in app.js to handle the intent and parse out the macro.

**Comment by jradwan** [comment]
Initial working feature added in 7208dd6. 

Basic overview (will write up a wiki page eventually):

- enable macros in config.json ("macros": true)
- define macros in macros.json (see example_macros.json for template):

    "name": "name to call macro by",
    "description": "description of what macro does (will be added to card)",
    "commands": "comma-separated list of commands" (see [TIVOCOMMAND_SLOT.txt](https://github.com/jradwan/alexa_tivo_control/blob/master/docs/TIVOCOMMAND_SLOT.txt) for available commands)
```
[
  {
    "name": "ENTER PIN",
    "description": "sample macro #3: enter parental controls PIN",
    "commands": "NUM1,NUM0,NUM1,NUM0"
  }
]
```
- to assist with voice matching of macro names, create custom TIVOMACRO_SLOT slot in Alexa interaction model, add macro names to slot
- use 'Alexa, tell TiVo to list macros' to hear list of defined macros (details added to card in Alexa app)
- use 'Alexa, tell TiVo to execute macro \<name\>' to run a macro

**Comment by jradwan** [comment]
Initial wiki documentation page [here](https://github.com/jradwan/alexa_tivo_control/wiki/Creating-and-Using-Macros).

**Comment by jradwan** [comment]
To add:
- pause/sleep in a command sequence
- call macro from another macro (for re-usability)

**Comment by vanstrien** [comment]
It looks like this breaks the Amazon config.  I get 

Error: There was a problem with your request: Unknown slot type 'TIVOMACRO_SLOT' for slot 'USERMACRO'

**Comment by jradwan** [comment]
Did you create the custom TIVOMACRO_SLOT in your Alexa interaction model? See new instructions [here](https://github.com/jradwan/alexa_tivo_control/wiki/Creating-and-Using-Macros).

**Comment by vanstrien** [comment]
That worked.  Thanks.  I still have issues with it not talking to my endpoint (even though I can hit it from the Internet) but I'll keep working on it.

**Comment by jradwan** [comment]
Cool. Let me know what kind of issue you're having (in another issue, if necessary) and I'll help if I can.

**Comment by jradwan** [comment]
Added WAIT macro command to "pause" the macro for a specified number of seconds in 0260d7c. Syntax is 'WAIT x' where x is the number of seconds you want the macro to pause/wait.

Sample macro using WAIT:

```
  {
    "name": "SLEEP TEST",
    "description": "test the sleep-pause feature",
    "commands": "LIVETV,NUM1,NUM1,NUM4,NUM8,ENTER,WAIT 5,NUM1,NUM0,NUM0,NUM8,ENTER,WAIT 10,NUM1,NUM0,NUM1,NUM3,ENTER"
  }
```
Drops to live TV, changes to channel 1148; waits 5 seconds then changes to channel 1008; waits 10 seconds then changes to channel 1013.
