### ISSUE TITLE
questions about installation on mac

### ISSUE THREAD

**Issue by TRingo1** [jradwan/alexa_tivo_control#4]
Jason, excellent work, not sure if this is the right place, i want to make a translate table to be able to change channels on alexa via tivo,  "Alexa change channel to ESPN" and have the tivo change to that channel.  also on a first note where are you running your alexa-app-server ? I'm trying to get running on my MacBook, and not sure of the base install directory of the node.js and node_modules folder seems to be the base.  i have used home-brew to install.  thanks again great work so far.

**Comment by jradwan** [comment]
Who's Jason? :-)

Doing something like that translate table for named channel changes is on my [To Do List](https://github.com/jradwan/alexa_tivo_control/wiki/To-Do-List), I just haven't had a lot of time to tinker lately. Maybe over the upcoming holiday break.

I'm running the alexa-app-server on a local Linux server. I'm not familiar with the home-brew install (did a quick read on it though) but the base directory should be one above node_modules (and server.js should be there as well). There should also be an apps directory there, and that's where alexa_tivo_control should go.

**Comment by TRingo1** [comment]
Thanks for the feed back, not sure who J*****? is either haha....  i am building a linux server, and going to use that to build my node.js system see if I'm can get that to work. MacBook is already doing to much.  thanks for publishing all your work, and comments.  this is great stuff! takes my mind of my day job and keeps me up all night!

**Comment by jradwan** [comment]
Thanks for the kind words! I'm just a tinkerer myself and it's fun to have other people interested in tinkering with the same stuff.
