### ISSUE TITLE
Run this skill on IIS?

### ISSUE THREAD

**Issue by maverickbluer1** [jradwan/alexa_tivo_control#40]
I have access to a Windows server with SSL running.  Could you provide any directions to serve your skill on that server?

**Comment by jradwan** [comment]
I've never used IIS, sorry. 😦 

You can't directly host the skill under a web server anyway ... it runs inside the alexa-app-server which has its own listening endpoint. You could probably proxy the SSL traffic _through_ IIS though, which is what I do with Apache.

https://docs.microsoft.com/en-us/iis/extensions/configuring-application-request-routing-arr/creating-a-forward-proxy-using-application-request-routing

**Comment by maverickbluer1** [comment]
Thanks for putting this up.  I installed on a Raspberry Pi and am using it now with as an AWS lambda.  Thanks again!

**Comment by jradwan** [comment]
Glad you got it working! If you do come up with IIS instructions, let me know and I'll add them here.
