### ISSUE TITLE
UK Tivo :  Installation wiki does not document the need for additional slot types like AMAZON.GENRE

### ISSUE THREAD

**Issue by asantaga** [jradwan/alexa_tivo_control#47]
When adding the skill to alexa you are required to create some slots for the utternances to work with. Alas in the UK multiple SLOT types are not supported, like AMAZON.GENRE.  Easy workaround is to remove the unneeded SLOT types

**Comment by jradwan** [comment]
I had no idea so many slot types weren't supported outside of the "English (U.S.)" language, sorry! Maybe they would work as custom slots, I'm not sure. This is a side-effect of switching the language from US to UK to avoid the problem you documented in issue #48. I'll have to think about how this could be handled ...

**Comment by asantaga** [comment]
Yeah sorry for the brief comments, ive only been looking at Alexa skills in the last week and lets say im a "noob" here..

**Comment by asantaga** [comment]
Here's an idea.. could we split the sample utterences into base and advanced?

UK Virgin tivo doesnt support all the bells and whistles of the US tivo's so the Base would make sense here.. 
US Tivos are more advanced and have apps  , which would include the 

Basic would include generic tivo functionality like changing channels, home, myshows etc and advanced would have the full big bang.. This could be controlled by a flag in config.json

**Comment by jradwan** [comment]
Not a bad idea ... sort of like the mini flag in config.json. I'll think about it ...

**Comment by asantaga** [comment]
fyi, Ive started a project to generate the UK Tivo Channels from public sources, should have it done , soon ish

**Comment by darrenkenny1983** [comment]
Hi, how do UK users get to use the feature of turning the tivo over by channel name when the AMAZON.TelevisionChannel slot type isn't available when en-gb language is selected when creating the skill.

**Comment by jradwan** [comment]
Probably need to use a custom slot instead. I'm surprised by the sudden influx of non-US users! 😁

**Comment by darrenkenny1983** [comment]
Tivo has a good presence in the U.K. due to virgin media using it on their boxes. Any help any of you can give me to get this part working would be great.

**Comment by asantaga** [comment]
guys, to help out I've created a PR with UK Virgin Channels channels.json file. Im no alexa expert but I agree I think to get channel by name working we'll need to use a custom slot..

**Comment by darrenkenny1983** [comment]
am i right in thinking that if we use a custom slot we will need to list all the channel names in it so alexa can match.

**Comment by asantaga** [comment]
reading up on Custom Slots, yes.. But using the sample channel list I created would make it trivial to generate this..

**Comment by jradwan** [comment]
Doing some initial research, this is the list of affected intents, right?

ListChannels
AMAZON.Genre

ChangeTiVoBox, ChangeChannel,PutOn, ForceChannel
AMAZON.Room

Search, Type
AMAZON.Movie
AMAZON.TVSeries

PutOn
AMAZON.TelevisionChannel

So if I can "hide" those intents (or modify what slots are used) based on language/region, would that make it easier for non-US users to get the skill running (meaning, less manual code changes to utterances and intents)? I'm thinking I'd have to use a custom slot and then the user would need to define the values for those slots themselves (like Rooms, Genres, and Television Channels).

Putting this here for reference as well: https://developer.amazon.com/docs/custom-skills/slot-type-reference.html#list-types

**Comment by jradwan** [comment]
Ok, took a quick initial shot at this tonight (see commit 34c22111):

I added a new "language" setting in config.json (set to "us", "uk", or "ca"). When this is _not_ "us" the AMAZON slot types will be replaced with custom ones:

- AMAZON.Genre -> TIVOGENRE_SLOT
- AMAZON.Room -> TIVOROOM_SLOT
- AMAZON.Movie -> TIVOMOVIE_SLOT
- AMAZON.TVSeries -> TIVOTVSERIES_SLOT
- AMAZON.TelevisionChannel -> TIVOTVCHANNEL_SLOT

You'll need to create those custom slot types on the Interaction Model tab of your Alexa Skill (like the TIVOCOMMAND_SLOT in step 13 of the [installation instructions](https://github.com/jradwan/alexa_tivo_control/wiki/Installation-Instructions)). You can fill them with valid values so you can actually use those intents (like listing channels by genre, controlling TiVos in different rooms, etc.). Searching for movies and TV shows won't really work unless you fill in the values you'll be searching for in TIVOMOVIE_SLOT and TIVOTVSERIES (not really practical). Put your channel names (from channels.json) in TIVOTVCHANNEL_SLOT to change channels by name. Or you can put a single "dummy" value in each slot if you're not actually going to use the related intents. When you're done, it should look something like this:

![image](https://user-images.githubusercontent.com/11047158/34137438-f34a5674-e438-11e7-8003-a54eafbc7a58.png)

Give it a shot and let me know what you think. This should at least help eliminate having to manually edit the generated intents and utterances for the interaction model.

**Comment by darrenkenny1983** [comment]
@jradwan great work, initial testing

**Comment by darrenkenny1983** [comment]
looks positive

**Comment by asantaga** [comment]
Im away from home atm, but i'll be testing later this week.
Also if its worth noting the uk tivo is called a "virgin tivo V6"

**Comment by asantaga** [comment]
Ok done some testing and got good results

1. Darrens right I need to rewrite the channel generator so that it generates lower case channel names  (on my list)
2. Sometimes I couldnt get it to detect the channel name.. it would say "cannot find bbc 1" , in the debug logs it would say " invalid channel bbc 1"...

Might have been me though.. 

Im going to rewrite the channel Generator in JavaScript and get it to generate two files, a UKTivoChannels.json and UKTIVO_CHANNELSLOT.json file..

**Comment by jradwan** [comment]
Try using "b.b.c. 1" or "b.b.c. one" in the channels JSON file. I find that using initials like that assists with recognition.

**Comment by asantaga** [comment]
Guys, I started rewriting the channel generator in JS but then thought, Im not sure its actually worth it.. I mean the channel numbers dont change , so unless someone voices another opinion I'll leave it as python and simply fix the file so it works better..  ?

**Comment by jradwan** [comment]
I thought about trying to use your channel generator to generate JSON files for other providers, but decided it's just easier to let the user create their own. And yes, since they don't change much, it's just some initial work and then minor corrections going forward. Thanks for contributing the UK Virgin list though! Glad to hear my initial changes for "internationalization" are working as well.

**Comment by asantaga** [comment]
Yeah, the problem with the generator is that its a crude webScraper, and depends totally on the webpage being scraped. It would need to be totally rewritten for any other provider as I think the page would change... Anyway, Im testing a new file, if it works better I'll upload it and then move onto the next ER, which is getting Apps to work properly.. Currently if you ask for youtube it goes to the wrong menu option.. 
But.... NEW YEARS EVE here today!! that takes precedence! 

Happy new year all!

**Comment by jradwan** [comment]
Closing this issue since I've added the language setting switch to work around the lack of slot types and added notes to the installation instructions accordingly. Thanks again for the contributions!
