### ISSUE TITLE
Doc Bug  :  Need to set language to English(UK) and not English(US)

### ISSUE THREAD

**Issue by asantaga** [jradwan/alexa_tivo_control#48]
Not really a bug, just logging this so people know. For UK people when creating the skill make sure you set the Language to English (UK) and not English(US). If you dont it wont work in the UK and Alexa will simply say "I dont know how to do that"

**Comment by jradwan** [comment]
Thanks for the tip. I've updated the screenshot and added a note to step 12 of the [installation instructions](https://github.com/jradwan/alexa_tivo_control/wiki/Installation-Instructions) to include this.
