### ISSUE TITLE
implementing issue24 of Alexa_utterences isnt clear

### ISSUE THREAD

**Issue by asantaga** [jradwan/alexa_tivo_control#49]
Whilst implementing this I noticed the following comment in the doc (step 13)
"For issue #24, you can just manually modify the index.js file for the alexa-utterances package with the code changes listed in the PR." 

I was kinda stumped at what this meant and then simply edited the file manually , however I think it might be worth documenting precisely (step by step here perhaps) what one would need to do to get the patch installed..

**Comment by jradwan** [comment]
I'm hopeful at some point that PR will be merged into the alexa-utterances package so this manual step won't be necessary. So I really don't want to write detailed documentation for something that's "temporary" like that. I'm assuming a certain level of technical prowess in the people who are attempting to use this skill. :)

That being said, I'll add a link to the [code change diff](https://github.com/alexa-js/alexa-utterances/pull/24/files#diff-168726dbe96b3ce427e7fedce31bb0bc) in issue #24 to make it easier to see.
