### ISSUE TITLE
Success, finally have all the parts working together! and now controlling my Tivo via my Echo

### ISSUE THREAD

**Issue by TRingo1** [jradwan/alexa_tivo_control#5]
I have successfully have NodeJS running Alexa-App-Server on my Macbook, and running HTTPS and HTTP.  this is pretty cool.  I have a couple of additions I'm working on adding, VolumeUp, VolumeDown, Mute and UnMute.  ill update pull a request and update code.

**Comment by jradwan** [comment]
I'm not sure how you'd implement the volume/mute controls. The TiVo doesn't actually control volume, your TV does. So when you program those keys on your remote, the "commands" are being sent by IR to your TV directly, not through the TiVo. In other words, what I'm saying is I don't think you can control the volume on your TV or receiver via the TiVo's telnet interface.

I know some TVs have HDMI-CEC, which _might_ work this way, but I don't have one like that to test and it certainly wouldn't be universally supported.
