### ISSUE TITLE
Nice to have preconfigured TIVO Channels.json file

### ISSUE THREAD

**Issue by asantaga** [jradwan/alexa_tivo_control#50]
As above. I think the data could be generated from sources like xmltv but needs some investigation..

I may produce the uk virgin tivo line up..  in a fork which can then be pulled

**Comment by jradwan** [comment]
Sure, feel free to share if you build that. It's harder to do in the US since there are so many providers with different lineups, and not everyone will use the "change channel by name" utterance so I just provide the template and leave it as an exercise for the user to define their own channels.json file.

**Comment by asantaga** [comment]
Ive created a UK Tivo Channels PR for you :-) I also added the python I wrote to generate it, I think the sample code could be used to generate channel files for other providers

**Comment by darrenkenny1983** [comment]
great work with the virgin media channel list. i have noticed that channel names need to be in lower case and channels like bbc one needs to be entered like bbc 1 as alexa is sending a 1 instead of the word "one".

**Comment by asantaga** [comment]
@darrenkenny1983 , your right.. The next step is to modify the generator (python based) to make these changes.. but until we get custom slots etc, I think its a moot point. Im going to see if I can help with the custom slots piece for channels and then I can look to clean up the channel list.

Curious : I used a piece of python to generate the list, I can add logic to it (like replace one to 1, lower case, bbc to b.b.c etc) etc, but how often do these channel numbers change??? Im thinking, use the code for a headstart and then simply edit the file manually right?

**Comment by jradwan** [comment]
Thanks for PR #52. I've included your sample python generator and moved the example config files into a separate examples directory.

**Comment by darrenkenny1983** [comment]
@asantaga channel numbers don’t really change that much. A quick win with the channel list generator is to set the Alias value to lowercase as that is the value that is used to Match against. Any help with building the custom slot would be gratefully received.

**Comment by asantaga** [comment]
@jradwan @darrenkenny1983  I'll tweak the code to set the alias to lower case (simple) soon 
I was also thinking that given the rest of the code is in JavaScript I'll probably rewrite the code in JS

**Comment by jradwan** [comment]
@asantaga cool, I'll leave this issue open for now then.

**Comment by asantaga** [comment]
Guys, given the UK tivo channels dont change often Ive decided to leave the generator code as python for now (its already written) and will concentrate on tweaking the file so that channels are recognized easier. Unless someone thinks otherwise Im gonna close this issue

**Comment by jradwan** [comment]
No worries ... thanks for the contribution!
