### ISSUE TITLE
Doesn’t work for English(CA)

### ISSUE THREAD

**Issue by kharder69** [jradwan/alexa_tivo_control#51]
How can I get this to work for Canada.  I get errors for any of the AMAZON.xxxxx intents.

**Comment by asantaga** [comment]
Alas I havent had time to do this properly, and I think the correct way to to do this is via the code (a flag) but here's a sample [Utterences file](https://gist.github.com/asantaga/a63aea0c8e4e307771e520215bc80f37) and a sample [intent schema](https://gist.github.com/asantaga/05acbd6b2ae39dd443c778d00a821a99) I am using for my tivo.

You will need to create the following SLOTS

TIVOCOMMAND_SLOT  : with all the normal stuff as noted in the wiki
TIVOMACRO_SLOT    : enter null
TIVOBOX    : 1
TIVOBOXRM  : 1

These were produced by simply editing out things I didnt want/need at the moment. I plan to do it properly when the wife allows me to tinker vs xmas shopping etc.

Hope this gets you going.. My next step is exposing the nodeJS to the internet without using grok.. I tired but i get errors... :-(

**Comment by kharder69** [comment]
Thanks I will try it today.

Appreciate the quick response.

Oh and one other question.  Should this skill work with echosim.io<http://echosim.io>?

Ken

On Dec 10, 2017, at 5:26 AM, Angelo <notifications@github.com<mailto:notifications@github.com>> wrote:


Alas I havent had time to do this properly, and I think the correct way to to do this is via the code (a flag) but here's a sample Utterences file<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgist.github.com%2Fasantaga%2Fa63aea0c8e4e307771e520215bc80f37&data=02%7C01%7C%7Cce561b6d17144bcc4c8108d53fb87769%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636484983856971537&sdata=Lp2lPNcBfttGBze%2BZrGv2Vet9cknQS9uVqbDMs%2FVJIw%3D&reserved=0> and a sample intent schema<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgist.github.com%2Fasantaga%2F05acbd6b2ae39dd443c778d00a821a99&data=02%7C01%7C%7Cce561b6d17144bcc4c8108d53fb87769%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636484983856971537&sdata=OUOIKc2vPQaF%2F2Mt2NNKg0Hre8V2C9tYDsp%2BO1dYStQ%3D&reserved=0> I am using for my tivo.

You will need to create the following SLOTS

TIVOCOMMAND_SLOT : with all the normal stuff as noted in the wiki
TIVOMACRO_SLOT : enter null
TIVOBOX : 1
TIVOBOXRM : 1

These were produced by simply editing out things I didnt want/need at the moment. I plan to do it properly when the wife allows me to tinker vs xmas shopping etc.

Hope this gets you going.. My next step is exposing the nodeJS to the internet without using grok.. I tired but i get errors... :-(

**Comment by asantaga** [comment]
Ken 

Not tried echosim but providing your logged into using the same account then yes should work..

Angelo

**Comment by jradwan** [comment]
I might have some time over the Christmas holiday (like @asantaga) to put in some sort of config switch for non-US users. PRs are always welcome. 😄

**Comment by jradwan** [comment]
I'm closing this ... let's track everything in issue #47.
