### ISSUE TITLE
Broken "macros" used to navigate to the video/audio providers (was: What TiVo has this been tested on?)

### ISSUE THREAD

**Issue by jg123** [jradwan/alexa_tivo_control#6]
The commands to get to Netflix, search, etc aren't quite working. I have a Bolt. What is your TiVo?

**Comment by jradwan** [comment]
I've tested on a Bolt, Roamio, and Mini. But I think my fix for issue #3 may have broken the "macros" used to navigate to the video/audio providers as I'm seeing something similar here now. Guess I didn't test enough before I committed that change. I'll look into it ...

**Comment by jradwan** [comment]
Ok, I think I've corrected this. I found a "better" way to fix the problem from issue #1 and issue #3 so hopefully the macros work again. Now I've noticed the order of the audio/video providers has changed, so there's a fix for that coming shortly as well.
