### ISSUE TITLE
Channel changing on Mini

### ISSUE THREAD

**Issue by jradwan** [jradwan/alexa_tivo_control#7]
The SETCH command doesn't work on the TiVo Mini, you have to use IRCODE instead. 

Ex. instead of just:

`SETCH1008`

you need to send

```
IRCODE NUM1
IRCODE NUM0
IRCODE NUM0
IRCODE NUM8
```

So some extra logic would be needed in order to "translate" the user's text/speech request into the multiple IRCODE commands.

**Comment by jradwan** [comment]
Use [AMAZON.NUMBER](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#number) slot type to convert spoken number into digits? Then split the resulting string one digit/character at a time to create the IRCODE command macro.

**Comment by TRingo1** [comment]
I was also looking at the 
AMAZON.TelevisionChannel

Names and abbreviations for television channels.

Examples:
◾abc
◾cartoon network
◾cnn
◾espn 2
◾nbc

This slot type can be used with skills in the following languages:
◾English (US)

**Comment by jradwan** [comment]
That will definitely be handy for adding the ability to change channels by name.
