### ISSUE TITLE
Launching Vevo is hit-and-miss

### ISSUE THREAD

**Issue by jradwan** [jradwan/alexa_tivo_control#9]
Launching Vevo from the tester works fine, but doing it via voice control with Alexa is hit-or-miss. I originally started with just "vevo" (or "veevo") in the utterance, but Alexa would just "bonk" as if she encountered an error or didn't understand the command. I temporarily changed the utterance to "booboo" and it worked fine every time.

Right now, I've got the utterance set to "vevo music" which seems to help, but sometimes she'll launch Plex Music, or won't understand the command.

The only thing I can think of is Vevo sounds too much like TiVo? Not sure what the issue is here but it's got to be with the voice recognition/translation on the Alexa side.

**Comment by TRingo1** [comment]
I was trying to update and test, and when I updated, it overwrote all my directories and config files, I had to rebuild from scratch, the second time was much faster, I was able to recreate the complete environment in 30 mins, and have working.  

My question is what is the best way to update alexa_tivo_controller and not have to build from scratch. 
I am also looking at updating the wiki to show Mac installation steps with SSL enabled.

**Comment by jradwan** [comment]
If you just do a 'git pull' in your alexa_tivo_control folder (for this repo) it should only pull down the changes. And since the config.json file isn't part of the repo, it shouldn't overwrite anything you've customized.

Also, this is an issue for Vevo, so this kind of discussion really belongs in a separate issue. ;-)

**Comment by jg123** [comment]
How about music videos as the keyword?

**Comment by jradwan** [comment]
Good idea ... done! (and it seems to work a lot better)
